#pipeline name/workflow
name:First workflow

jobs:
    print-message:
      runs-on:ubuntu-latest

      steps:
        
          -name:print welcome message
           run: echo'welcome to github action'

          
          -name: print hello message
            run:echo 'hello....'


